name: tharad_tech
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  flutter_bloc: ^8.1.1
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.12
  pinput: ^5.0.1
  json_serializable: ^6.8.0
  build_runner: ^2.3.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.2.0
  freezed: ^2.5.2
  dio: ^5.1.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  retrofit_generator: 
  get_it: ^7.6.0
  shared_preferences: ^2.3.2  
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
